# Generated by Django 2.2.6 on 2019-11-20 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id_admin', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_admin', models.CharField(max_length=120)),
                ('contrasenia_admin', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('dni_cliente', models.IntegerField()),
                ('nombre_cliente', models.CharField(max_length=120)),
                ('apellidos_cliente', models.CharField(max_length=120)),
                ('correo_cliente', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_producto', models.TextField()),
                ('nombre_producto', models.CharField(max_length=280)),
                ('precio_producto', models.IntegerField()),
                ('imagen_producto', models.ImageField(upload_to='productos_imagenes')),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id_cita', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_cita', models.TextField()),
                ('fecha_cita', models.DateTimeField()),
                ('id_cli_cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decohome.Cliente')),
            ],
        ),
    ]
